name: diabetes_regression_v1

dependencies:

  # The python interpreter version.
- python=3.7.5

  # Required by azureml-core, installed separately through Conda to
  # get a prebuilt version and not require build tools for the install.
- psutil=5.6 #latest

- numpy=1.18.1
- pandas=1.0.0
- scikit-learn=0.22.1
#- r-essentials
#- tensorflow
#- keras

- pip=20.0.2
- pip:
  - azureml-core==1.0.79
  - inference-schema[numpy-support]==1.0.1
