trigger: none
pr:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

variables:
- template: azdo-variables.yml
- group: devopsforai-aml-vg

jobs:
- template: azdo-base-pipeline.yml
