trigger: none
pr:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

container:
  image: acralgattik86.azurecr.io/a20200130pr150
  endpoint: ContainerRegistry

variables:
- template: diabetes_regression-variables.yml
- group: devopsforai-aml-vg

steps:
- template: azdo-base-pipeline.yml
