trigger: none
pr:
  branches:
    include:
    - master

pool: 
  vmImage: 'ubuntu-latest'

container:
  image: acralgattik86c.azurecr.io/a20200130ceaa
  endpoint: ContainerRegistryC

variables:
- template: diabetes_regression-variables.yml
- group: devopsforai-aml-vg


steps:
- template: azdo-base-pipeline.yml
