trigger: none
pr:
  branches:
    include:
    - master

pool: 
  vmImage: 'ubuntu-latest'

container:
      image: mcr.microsoft.com/mlops/python:latest
      endpoint: XXX


variables:
- template: azdo-variables.yml
- group: devopsforai-aml-vg


steps:
- template: azdo-base-pipeline.yml
