trigger: none
pr:
  branches:
    include:
    - master

pool: 
  vmImage: 'ubuntu-latest'

container: acrmlopssampledev.azurecr.io/modelbuild:latest


variables:
- template: azdo-variables.yml
- group: devopsforai-aml-vg


steps:
- template: azdo-base-pipeline.yml
