pr: none
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - infrastructure/

variables:
- group: terraform

stages:
- template: terraform-stages-template.yml
  parameters:
    environment: stage
    displayName: Staging
